server:
  port: 80
  #servlet:
  #   context-path: /Graba

spring:
  datasource:
     driverClassName: org.h2.Driver
     url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
     username: sa
     password:
     hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
       # hbm2ddl:
       # auto: create-drop 
       # ddl-auto:  
#    password: pass
#    url: jdbc:mysql://localhost:3306/jdbc_authentication
#    url: jdbc://mqsql:localhost:3306/graba
#    username: root
  jpa:
    show-sql: true  
    hibernate:
      ddl-auto: none
   # generate-ddl: true
  mail:
     host: smtp.gmail.com
     port: 587
     username: grabalocal@gmail.com
     password: xxxx
     tls: true
     protocol: smtp
     properties:
        mail:
           smtp:
              auth: true
              starttls.enable: true
              ssl.trust: smtp.gmail.com
  logging:
    level:
      org:
        springframework:
          security: DEBUG     
        hibernate:
          SQL: DEBUG   
          
          
 #http://localhost/h2-console/login.do?jsessionid=e0f98f6cfea122285ca7806293a9a12a         